services:
    postgres:
        image: "maurodatamapper/postgres:12.14-alpine"
        build: ./postgres
        shm_size: 512mb
        environment:
            POSTGRES_PASSWORD: postgresisawesome
        volumes:
            - postgres12:/var/lib/postgresql/data
        restart: on-failure

        # If we want to connect to the server from outside
        ports:
          - 5432:5432

    mauro-data-mapper:
        image: "maurodatamapper/mauro-data-mapper:${MDM_TAG}"
        build:
            context: mauro-data-mapper
            args:
                MDM_APPLICATION_COMMIT: "${MDM_APPLICATION_COMMIT}"
                MDM_UI_COMMIT: "${MDM_UI_COMMIT}"
                ADDITIONAL_PLUGINS: "uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-nhs-data-dictionary:2.0.0-SNAPSHOT;uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-authentication-openid-connect:2.2.0"
                MDM_UI_THEME_NAME: "nhs-digital"
                CACHE_BURST: "${CACHE_BURST}"
                NHSD_DD_ORCHESTRATION_API_ENDPOINT: "${MAURO_API_ENDPOINT}"
                NHSD_DD_MAURO_BASEURL: "${MAURO_ENDPOINT}"
        environment:
            PGPASSWORD: postgresisawesome
            runtime.config.path: /usr/local/tomcat/conf/runtime.yml
            maurodatamapper.authority.name: NHS Data Dictionary
            maurodatamapper.authority.url: https://www.datadictionary.nhs.uk/
        ports:
            - "${MDM_PORT}:8080"
        depends_on:
            - postgres
        volumes:
            - lucene_index:/lucene
            - ./shared_volumes/logs/maurodatamapper:/usr/local/tomcat/logs
            - ./shared_volumes/tmp:/tmp
            - ./mauro-data-mapper/config/runtime.yml:/usr/local/tomcat/conf/runtime.yml
        restart: on-failure
# Persistence capability to systems,
# Any volumes labelled below will ensure persistence when containers removed unless the volume is removed as well
volumes:
    postgres12:
        driver: local
    lucene_index:
        driver: local
